version: '3.7'

services:
  postgres:
    image: postgres:13
    environment:
      POSGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn src.app:app --host 0.0.0.0 --port 5000 --reload
    ports:
      - 5000:5000
    depends_on:
      - postgres
    volumes:
    - .:/www
