version: '3.7'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 10240000000
    ports:
      - 5432:5432

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn src.app:app --host 0.0.0.0 --port 5000 --loop uvloop --reload
    ports:
      - 5000:5000
    depends_on:
      - postgres
      - jaeger
    volumes:
      - .:/www
    env_file:
      - ./.env

  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - 16686:16686  # webui
      - 14268:14268  # http collector format=jaeger.thrift

#  minio:
#    image: minio/minio
#    ports:
#      - 9000:9000
#      - 9001:9001
#      - 39271:39271
#    command: server /data --console-address :9001
#    volumes:
#      - ./.docker/minio:/data
#    environment:
#      - MINIO_ROOT_USER=minioadmin
#      - MINIO_ROOT_PASSWORD=minioadmin
