[tox]
envlist = py310
isolated_build = true

[testenv]
allowlist_externals=poetry
setenv =
    PG_DSN = postgresql://postgres:postgres@localhost:5432/test

commands =
    pip install -r requirements.txt
    isort src tests
    mypy src tests
    - pylint src tests
    pytest --cov-report term --cov=src -vvv --asyncio-mode=auto --disable-warnings tests/
