apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.postgres.name}}-{{ .Release.Namespace }}
  labels:
    app: {{ .Values.postgres.name}}
    namespace: {{ .Release.Namespace }}
spec:
  accessModes: {{ .Values.postgres.pvc.accessModes }}
  resources:
    requests:
      storage: {{ .Values.postgres.pvc.storage }}
