global:
  hostname: k8s.local

app:
  version: 0.0.0
  name: api
  image: sane4eg/fapi:drop_jaeger_1
  replicas: 3
  ports:
    - name: http
      containerPort: 5000
      protocol: TCP
  env:
    - name: LOG_FORMATTER
      value: json
    - name: LOG_LEVEL
      value: INFO
    - name: DB_CONNECTION_STRING
      value: postgresql://postgres:postgres@postgres:5432/postgres

postgres:
  name: postgres
  image: postgres:13
  replicas: 1
  ports:
    - name: tcp
      containerPort: 5432
      protocol: TCP
  service:
    ports:
      - protocol: TCP
        port: 5432
        targetPort: 5432
  pvc:
    accessModes: ["ReadWriteOnce"]
    storage: "1Gi"
    containerPath: "/var/lib/postgresql/data"
  env:
    - name: POSTGRES_USER
      value: postgres
    - name: POSTGRES_DB
      value: postgres
    - name: POSTGRES_PASSWORD
      value: postgres
