apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: {{ .Values.app.name}}
  namespace: {{ .Release.Namespace }}
spec:
  rules:
    - host: {{ .Values.app.name }}.{{ .Release.Namespace }}.{{ .Values.global.hostname }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.app.name }}
                port:
                  number: 80
