apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.app.name }}
    namespace: {{ .Release.Namespace }}
  ports:
      - name: http
        protocol: TCP
        port: 80
        targetPort: 5000
